### ISSUE TITLE
Merge LIO changes with latest versions

### ISSUE THREAD

**Issue by karliss** [lio-lv/cms#4]
Create lio-v1.3 branch and update lio branch from master.

**Comment by andreyv** [comment]
I merged master into the lio branch with conflict resolution in 729ec17cf36a0925a140fc26b81d983df4a1ef8a.

Notable changes:
- Added `{% module xsrf_form_html() %}`
- Replaced `url_root` with `url()`

Now we need to double-check differences with master (https://github.com/cms-dev/cms/compare/master...lio-lv:lio) and test that local additions still work properly.

**Comment by andreyv** [comment]
The `lio` branch should now be up to date with master again.

There are more upstream changes upcoming in CMS `jinja_aws` branch.

**Comment by andreyv** [comment]
Fixed in c3f82f7faa56b484b3d84030719816a6ae602543, bd6965a96eaf946bd40f22bdd4555747a3b4988e, 6c178e621594ce860c5abd61e714287987e49ed9, acff1d5037e46ff478d1d5db9b07a03284e42d88, 45621be6e4d630af68d34dda96f6df65d585f0a2 and more.

The branch is now up to date with master.
